-- 1. Locations table
CREATE TABLE Locations (
    LocationID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    LocationName VARCHAR2(100) 
);

DELETE FROM Patients;
DELETE FROM Locations;

Drop Table Patients;

-- 2. Insurance table
CREATE TABLE Insurance (
    InsuranceID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    HasInsurance CHAR(1) CHECK (HasInsurance IN ('Y', 'N')),
    InsuranceType VARCHAR2(100)
);



-- 3. Patients table
CREATE TABLE Patients (
    PatientID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FirstName VARCHAR2(50) ,
    LastName VARCHAR2(50),
    Age NUMBER(3) CHECK (Age >= 0),
    Gender VARCHAR2(10) CHECK (Gender IN ('Male', 'Female', 'Other')) ,
    Email VARCHAR2(100),
    Phone VARCHAR2(20),
    WeightKg NUMBER(5),
    HeightCm NUMBER(5),
    BMI NUMBER(5,2),
    AgeGroup VARCHAR2(20),
    LocationID NUMBER,
    InsuranceID NUMBER,
    FOREIGN KEY (LocationID) REFERENCES Locations(LocationID),
    FOREIGN KEY (InsuranceID) REFERENCES Insurance(InsuranceID)
);

-- 4. MedicalRecords table
CREATE TABLE MedicalRecords (
    RecordID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PatientID NUMBER,
    Complaint VARCHAR2(255),
    Symptoms VARCHAR2(255),
    SymptomsDuration VARCHAR2(100),
    FOREIGN KEY (PatientID) REFERENCES Patients(PatientID)
);


SELECT * FROM LOCATIONS;


SELECT constraint_name
FROM user_constraints
WHERE table_name = 'PATIENTS';


SELECT constraint_name,
       constraint_type,
       search_condition
FROM user_constraints
WHERE table_name = 'PATIENTS';


ALTER TABLE Patients DROP CONSTRAINT SYS_C009525;


ALTER TABLE Patients
ADD CONSTRAINT chk_gender CHECK (Gender IN ('Man', 'Woman'));


-- 1. Create a backup of Locations (structure only, no data)
CREATE TABLE Locations_backup AS SELECT * FROM Locations WHERE 1=0;

-- 2. Drop the Locations table
DROP TABLE Locations CASCADE CONSTRAINTS;

-- 3. Recreate Locations without IDENTITY property
CREATE TABLE Locations (
    LocationID NUMBER PRIMARY KEY,
    City VARCHAR2(100)
);


INSERT INTO Locations (LocationID, City)
SELECT LocationID, LocationName
FROM Locations_Unique;


ALTER TABLE Patients
ADD CONSTRAINT fk_patient_location
FOREIGN KEY (LocationID) REFERENCES Locations(LocationID);



SELECT constraint_name, search_condition
FROM user_constraints
WHERE table_name = 'INSURANCE'
AND constraint_type = 'C';


ALTER TABLE Insurance
DROP CONSTRAINT SYS_C009521;


ALTER TABLE Insurance
ADD CONSTRAINT chk_hasinsurance
CHECK (HasInsurance IN ('Yes', 'No'));

ALTER TABLE Insurance
DROP CONSTRAINT chk_hasinsurance;


ALTER TABLE Insurance
MODIFY HasInsurance VARCHAR2(100);

ALTER TABLE Insurance
ADD CONSTRAINT chk_hasinsurance
CHECK (HasInsurance IN ('Yes', 'No'));

SELECT * FROM INSURANCE;








