-- Hospitals Table (if not already created)
CREATE TABLE Hospitals (
    HospitalID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    HospitalName VARCHAR2(200) NOT NULL,
    City VARCHAR2(100)
);

-- Diseases Table
CREATE TABLE Diseases (
    DiseaseID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DiseaseName VARCHAR2(200) NOT NULL
);

-- Junction Table to connect Diseases and Hospitals (many-to-many)
CREATE TABLE Disease_Hospitals (
    DiseaseID NUMBER NOT NULL,
    HospitalID NUMBER NOT NULL,
    PRIMARY KEY (DiseaseID, HospitalID),
    CONSTRAINT fk_disease FOREIGN KEY (DiseaseID) REFERENCES Diseases(DiseaseID),
    CONSTRAINT fk_hospital FOREIGN KEY (HospitalID) REFERENCES Hospitals(HospitalID)
);


INSERT INTO Hospitals (HospitalName, City) VALUES ('Hospital Biela?ski', 'Warszawa');
INSERT INTO Hospitals (HospitalName, City) VALUES ('Hospital Czerniakowski', 'Warszawa');
INSERT INTO Hospitals (HospitalName, City) VALUES ('Uniwersyteckie Centrum Kliniczne', 'Gdansk');
INSERT INTO Hospitals (HospitalName, City) VALUES ('Copernicus Hospital', 'Gdansk');
INSERT INTO Hospitals (HospitalName, City) VALUES ('Uniwersytet Szpital Kliniczny', 'Olsztyn');
INSERT INTO Hospitals (HospitalName, City) VALUES ('Szpital Wojewódzki', 'Olsztyn');
INSERT INTO Hospitals (HospitalName, City) VALUES ('Uniwersytecki Szpital Kliniczny', 'Bia?ystok');
INSERT INTO Hospitals (HospitalName, City) VALUES ('Centralny Szpital Kliniczny Uniwersytetu Medycznego', '?ód?');
INSERT INTO Hospitals (HospitalName, City) VALUES ('Szpital Jana Pawla II', 'Kraków');
INSERT INTO Hospitals (HospitalName, City) VALUES ('Wojewódzki Szpital Specjalistyczny im. J. Gromkowskiego', 'Wroc?aw');

SELECT * FROM HOSPITALS;


INSERT INTO Diseases (DiseaseName) VALUES ('Acid reflux');
INSERT INTO Diseases (DiseaseName) VALUES ('Acne');
INSERT INTO Diseases (DiseaseName) VALUES ('ADHD');
INSERT INTO Diseases (DiseaseName) VALUES ('Acute Abdominal Emergencies');
INSERT INTO Diseases (DiseaseName) VALUES ('Acute Respiratory Failure');
INSERT INTO Diseases (DiseaseName) VALUES ('Addiction');
INSERT INTO Diseases (DiseaseName) VALUES ('Adrenal Disorders');
INSERT INTO Diseases (DiseaseName) VALUES ('AIDS');
INSERT INTO Diseases (DiseaseName) VALUES ('Allergic Rhinitis');
INSERT INTO Diseases (DiseaseName) VALUES ('Anaphylaxis');
INSERT INTO Diseases (DiseaseName) VALUES ('Anemia');
INSERT INTO Diseases (DiseaseName) VALUES ('aneurysms');
INSERT INTO Diseases (DiseaseName) VALUES ('Appendicitis');
INSERT INTO Diseases (DiseaseName) VALUES ('Arterial Diseases');
INSERT INTO Diseases (DiseaseName) VALUES ('Arthritis');
INSERT INTO Diseases (DiseaseName) VALUES ('Asthma');
INSERT INTO Diseases (DiseaseName) VALUES ('Autoimmune and Inflammatory Disorders');
INSERT INTO Diseases (DiseaseName) VALUES ('Autoimmune Disorders');
INSERT INTO Diseases (DiseaseName) VALUES ('Back/neck pain');
INSERT INTO Diseases (DiseaseName) VALUES ('Bacterial Infections');
INSERT INTO Diseases (DiseaseName) VALUES ('Benign Tumors');
INSERT INTO Diseases (DiseaseName) VALUES ('Blocked arteries');
INSERT INTO Diseases (DiseaseName) VALUES ('Bleeding Disorders');
INSERT INTO Diseases (DiseaseName) VALUES ('Blood Disorders');
INSERT INTO Diseases (DiseaseName) VALUES ('Bone Diseases');
INSERT INTO Diseases (DiseaseName) VALUES ('Bone Disorders');
INSERT INTO Diseases (DiseaseName) VALUES ('Bone infections');
INSERT INTO Diseases (DiseaseName) VALUES ('Brain Disorders');
INSERT INTO Diseases (DiseaseName) VALUES ('Breast Cancer');
INSERT INTO Diseases (DiseaseName) VALUES ('Breast Cancers');
INSERT INTO Diseases (DiseaseName) VALUES ('Broken bones');
INSERT INTO Diseases (DiseaseName) VALUES ('Burns');
INSERT INTO Diseases (DiseaseName) VALUES ('Butterfly Rash');
INSERT INTO Diseases (DiseaseName) VALUES ('Cancer');
INSERT INTO Diseases (DiseaseName) VALUES ('Cardiomyopathies');
INSERT INTO Diseases (DiseaseName) VALUES ('Chest Trauma');
INSERT INTO Diseases (DiseaseName) VALUES ('Childbirth');
INSERT INTO Diseases (DiseaseName) VALUES ('Chronic Urticaria');
INSERT INTO Diseases (DiseaseName) VALUES ('Clotting Disorders');
INSERT INTO Diseases (DiseaseName) VALUES ('Colon polyps/cancer');
INSERT INTO Diseases (DiseaseName) VALUES ('Complex multisystem diseases');
INSERT INTO Diseases (DiseaseName) VALUES ('Contact Dermatitis');
INSERT INTO Diseases (DiseaseName) VALUES ('COPD');
INSERT INTO Diseases (DiseaseName) VALUES ('Coronary Artery Disease');
INSERT INTO Diseases (DiseaseName) VALUES ('Cosmetic Surgery');
INSERT INTO Diseases (DiseaseName) VALUES ('Covid-19');
INSERT INTO Diseases (DiseaseName) VALUES ('Cysts');
INSERT INTO Diseases (DiseaseName) VALUES ('Dental Abnormalities');
INSERT INTO Diseases (DiseaseName) VALUES ('Depression');
INSERT INTO Diseases (DiseaseName) VALUES ('Diabetes');
INSERT INTO Diseases (DiseaseName) VALUES ('Dialysis Access');
INSERT INTO Diseases (DiseaseName) VALUES ('Digestive System Cancers');
INSERT INTO Diseases (DiseaseName) VALUES ('Dislocations');
INSERT INTO Diseases (DiseaseName) VALUES ('Drug Allergies');
INSERT INTO Diseases (DiseaseName) VALUES ('Ear Disorders');
INSERT INTO Diseases (DiseaseName) VALUES ('Eating Disorders');
INSERT INTO Diseases (DiseaseName) VALUES ('Eczema');
INSERT INTO Diseases (DiseaseName) VALUES ('Endocrine Cancers');
INSERT INTO Diseases (DiseaseName) VALUES ('Epilepsy');
INSERT INTO Diseases (DiseaseName) VALUES ('Eye Diseases and Infections');
INSERT INTO Diseases (DiseaseName) VALUES ('Facial Fracture');
INSERT INTO Diseases (DiseaseName) VALUES ('Facial Trauma');
INSERT INTO Diseases (DiseaseName) VALUES ('Fetal Medicine');
INSERT INTO Diseases (DiseaseName) VALUES ('Food Allergies');
INSERT INTO Diseases (DiseaseName) VALUES ('Fractures');
INSERT INTO Diseases (DiseaseName) VALUES ('Gastritis');
INSERT INTO Diseases (DiseaseName) VALUES ('Gallstones');
INSERT INTO Diseases (DiseaseName) VALUES ('Genetic and Metabolic Disorders');
INSERT INTO Diseases (DiseaseName) VALUES ('Gout');
INSERT INTO Diseases (DiseaseName) VALUES ('Gynecologic Oncology');
INSERT INTO Diseases (DiseaseName) VALUES ('Hair and Nail Disorders');
INSERT INTO Diseases (DiseaseName) VALUES ('Hand and Wrist Conditions');
INSERT INTO Diseases (DiseaseName) VALUES ('Head and Neck');
INSERT INTO Diseases (DiseaseName) VALUES ('Head and Neck Surgery');
INSERT INTO Diseases (DiseaseName) VALUES ('Heart Conditions');
INSERT INTO Diseases (DiseaseName) VALUES ('Heart Diseases');
INSERT INTO Diseases (DiseaseName) VALUES ('Heart Failure');
INSERT INTO Diseases (DiseaseName) VALUES ('Hepatitis');
INSERT INTO Diseases (DiseaseName) VALUES ('HIV');
INSERT INTO Diseases (DiseaseName) VALUES ('Hormone Therapy');
INSERT INTO Diseases (DiseaseName) VALUES ('Hyperhidrosis');
INSERT INTO Diseases (DiseaseName) VALUES ('Hyperthyroidism');
INSERT INTO Diseases (DiseaseName) VALUES ('Hypothyroidism');
INSERT INTO Diseases (DiseaseName) VALUES ('Infant Feeding difficulties');
INSERT INTO Diseases (DiseaseName) VALUES ('Infections');
INSERT INTO Diseases (DiseaseName) VALUES ('Infections and Inflammation');
INSERT INTO Diseases (DiseaseName) VALUES ('Inflammatory Bowel Disease');
INSERT INTO Diseases (DiseaseName) VALUES ('Inflammatory/Infectious Conditions');
INSERT INTO Diseases (DiseaseName) VALUES ('Infertility');
INSERT INTO Diseases (DiseaseName) VALUES ('Insect Venom Allergies');
INSERT INTO Diseases (DiseaseName) VALUES ('internal bleeding');
INSERT INTO Diseases (DiseaseName) VALUES ('Joint Damage');
INSERT INTO Diseases (DiseaseName) VALUES ('Joint replacements');
INSERT INTO Diseases (DiseaseName) VALUES ('Kidney Diseases');
INSERT INTO Diseases (DiseaseName) VALUES ('Kidney stones');
INSERT INTO Diseases (DiseaseName) VALUES ('Kidney Transplants');
INSERT INTO Diseases (DiseaseName) VALUES ('Liver Diseases');
INSERT INTO Diseases (DiseaseName) VALUES ('Liver Transplants');
INSERT INTO Diseases (DiseaseName) VALUES ('Low Birth Weight');
INSERT INTO Diseases (DiseaseName) VALUES ('Lung abscesses');
INSERT INTO Diseases (DiseaseName) VALUES ('Lung Cancer');
INSERT INTO Diseases (DiseaseName) VALUES ('Lung Diseases');
INSERT INTO Diseases (DiseaseName) VALUES ('Lung Transplants');
INSERT INTO Diseases (DiseaseName) VALUES ('Lymphatic Disorders');
INSERT INTO Diseases (DiseaseName) VALUES ('Menstrual Irregularities');
INSERT INTO Diseases (DiseaseName) VALUES ('Metabolic Disorders');
INSERT INTO Diseases (DiseaseName) VALUES ('Minimally Invasive Surgery');
INSERT INTO Diseases (DiseaseName) VALUES ('monitor diseases');
INSERT INTO Diseases (DiseaseName) VALUES ('Morning Stiffness');
INSERT INTO Diseases (DiseaseName) VALUES ('Movement Disorders');
INSERT INTO Diseases (DiseaseName) VALUES ('Multiple sclerosis (MS)');
INSERT INTO Diseases (DiseaseName) VALUES ('Muscle and Neuromuscular Diseases');
INSERT INTO Diseases (DiseaseName) VALUES ('muscle strains');
INSERT INTO Diseases (DiseaseName) VALUES ('Nose and Sinus Conditions');
INSERT INTO Diseases (DiseaseName) VALUES ('Obesity');
INSERT INTO Diseases (DiseaseName) VALUES ('Organ Failure');
INSERT INTO Diseases (DiseaseName) VALUES ('Orthopedic Disorders');
INSERT INTO Diseases (DiseaseName) VALUES ('Orthopedic Surgery');
INSERT INTO Diseases (DiseaseName) VALUES ('Osteoporosis');
INSERT INTO Diseases (DiseaseName) VALUES ('Pancreas Transplants');
INSERT INTO Diseases (DiseaseName) VALUES ('Parasitic Infections');
INSERT INTO Diseases (DiseaseName) VALUES ('Parkinson''s disease');
INSERT INTO Diseases (DiseaseName) VALUES ('Patients requiring blood transfusions');
INSERT INTO Diseases (DiseaseName) VALUES ('Pelvic Inflammatory Disease');
INSERT INTO Diseases (DiseaseName) VALUES ('Pelvic Organ Prolapse');
INSERT INTO Diseases (DiseaseName) VALUES ('Personality Disorders');
INSERT INTO Diseases (DiseaseName) VALUES ('Pleural Diseases');
INSERT INTO Diseases (DiseaseName) VALUES ('Poisoning/Overdose');
INSERT INTO Diseases (DiseaseName) VALUES ('Post-cardiac surgery');
INSERT INTO Diseases (DiseaseName) VALUES ('Post-fracture rehabilitation');
INSERT INTO Diseases (DiseaseName) VALUES ('Post-Surgical Critical Care');
INSERT INTO Diseases (DiseaseName) VALUES ('Prematurity Care');
INSERT INTO Diseases (DiseaseName) VALUES ('Pregnancy');
INSERT INTO Diseases (DiseaseName) VALUES ('Prostate Diseases');
INSERT INTO Diseases (DiseaseName) VALUES ('Pulmonary embolism');
INSERT INTO Diseases (DiseaseName) VALUES ('Recovery from orthopedic surgeries');
INSERT INTO Diseases (DiseaseName) VALUES ('Refractive Errors');
INSERT INTO Diseases (DiseaseName) VALUES ('Retinal Disorders');
INSERT INTO Diseases (DiseaseName) VALUES ('Sepsis and Septic Shock');
INSERT INTO Diseases (DiseaseName) VALUES ('Schizophrenia');
INSERT INTO Diseases (DiseaseName) VALUES ('Severe injuries');
INSERT INTO Diseases (DiseaseName) VALUES ('Skin Cancer');
INSERT INTO Diseases (DiseaseName) VALUES ('Skin Cancers');
INSERT INTO Diseases (DiseaseName) VALUES ('Sleep Disorders');
INSERT INTO Diseases (DiseaseName) VALUES ('Soft Tissue Cancers');
INSERT INTO Diseases (DiseaseName) VALUES ('Soft Tissue Sarcomas');
INSERT INTO Diseases (DiseaseName) VALUES ('spinal cord injuries');
INSERT INTO Diseases (DiseaseName) VALUES ('Spinal Cord and Nerve Disorders');
INSERT INTO Diseases (DiseaseName) VALUES ('Spinal Disorders');
INSERT INTO Diseases (DiseaseName) VALUES ('Spinal Inflammation');
INSERT INTO Diseases (DiseaseName) VALUES ('Sport Injuries');
INSERT INTO Diseases (DiseaseName) VALUES ('Stomach cancer');
INSERT INTO Diseases (DiseaseName) VALUES ('Strokes');
INSERT INTO Diseases (DiseaseName) VALUES ('Strictures or tumors');
INSERT INTO Diseases (DiseaseName) VALUES ('Testicular Conditions');
INSERT INTO Diseases (DiseaseName) VALUES ('Throat and Voice Disorders');
INSERT INTO Diseases (DiseaseName) VALUES ('Thyroid cancer');
INSERT INTO Diseases (DiseaseName) VALUES ('Thyroid Eye Disease');
INSERT INTO Diseases (DiseaseName) VALUES ('Thyroid nodules');
INSERT INTO Diseases (DiseaseName) VALUES ('Thyroid/Parathyroid Tumors');
INSERT INTO Diseases (DiseaseName) VALUES ('Tissue Diseases');
INSERT INTO Diseases (DiseaseName) VALUES ('Torn ligaments');
INSERT INTO Diseases (DiseaseName) VALUES ('Trauma and Emergencies');
INSERT INTO Diseases (DiseaseName) VALUES ('Trauma Care');
INSERT INTO Diseases (DiseaseName) VALUES ('Transplant recipients/donors');
INSERT INTO Diseases (DiseaseName) VALUES ('Tropical Diseases');
INSERT INTO Diseases (DiseaseName) VALUES ('Tuberculosis');
INSERT INTO Diseases (DiseaseName) VALUES ('Tumors');
INSERT INTO Diseases (DiseaseName) VALUES ('ulcers');
INSERT INTO Diseases (DiseaseName) VALUES ('unexplained anemia or jaundice');
INSERT INTO Diseases (DiseaseName) VALUES ('Varicose Veins');
INSERT INTO Diseases (DiseaseName) VALUES ('Vascular Diseases');
INSERT INTO Diseases (DiseaseName) VALUES ('Venous Diseases');

SELECT * FROM DISEASES;