CREATE TABLE Insurance_Unique (
    InsuranceID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    HasInsurance VARCHAR2(100) CHECK (HasInsurance IN ('Yes','No')),
    InsuranceType VARCHAR2(100)
);

INSERT INTO Insurance_Unique (HasInsurance, InsuranceType)
SELECT DISTINCT HasInsurance, InsuranceType
FROM Insurance;

SELECT * FROM Insurance



-- 1. Create a backup of Locations (structure only, no data)
CREATE TABLE Insurance_backup AS SELECT * FROM INSURANCE WHERE 1=0;

-- 2. Drop the Locations table
DROP TABLE INSURANCE CASCADE CONSTRAINTS;

-- 3. Recreate Locations without IDENTITY property
CREATE TABLE INSURANCE (
    InsuranceID NUMBER PRIMARY KEY,
    HAS_INSURANCE VARCHAR2(100),
    INSURANCE_TYPE VARCHAR2(100)
);


INSERT INTO INSURANCE (InsuranceID, HAS_INSURANCE,INSURANCE_TYPE )
SELECT InsuranceID, HASINSURANCE,INSURANCETYPE
FROM INSURANCE_UNIQUE;

Select * from Patients;
Delete  From Patients;





