CREATE TABLE Locations_Unique (
    LocationID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    LocationName VARCHAR2(100)
);

INSERT INTO Locations_Unique (LocationName)
SELECT DISTINCT LocationName
FROM Locations;

Select * From LOCATIONS;
